on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # 1: Build - tests
  build:
    uses: MigracaoDotNetForms/Projeto_Windows/.github/workflows/build.yml@main
    with:
     build_configuration: 'Release'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      

  #3: deploy
  deploy:
    needs: build
    uses:  MigracaoDotNetForms/ci-cd-pipelines/.github/workflows/release-deploy.yml@main
 